/** Private owner-only deployment. Never publish this as an anonymous web app. */
const DB_ID='1caJ7plf4SWSWksu2lq_XvJkNBKyZVgof0RpoSOWDVUc';
const STORE='_자동화저장';
function setup(){
 const props=PropertiesService.getScriptProperties(),email=Session.getEffectiveUser().getEmail();
 if(!email)throw Error('관리자 Google 계정에서 실행해주세요.');
 const previous=props.getProperty('OWNER');if(previous&&previous!==email)throw Error('관리자 계정이 다릅니다.');
 props.setProperty('OWNER',email);
 const ss=SpreadsheetApp.openById(DB_ID);if(!ss.getSheetByName(STORE))ss.insertSheet(STORE).appendRow(['버전','조각','JSON']);
}
function authorize_(){const owner=PropertiesService.getScriptProperties().getProperty('OWNER'),active=Session.getActiveUser().getEmail();if(!owner||!active||active!==owner)throw Error('등록된 관리자 계정으로 로그인해주세요.');}
function withLock_(fn){const lock=LockService.getScriptLock();lock.waitLock(20000);try{return fn()}finally{lock.releaseLock()}}
function read_(){const props=PropertiesService.getScriptProperties(),revision=Number(props.getProperty('REV')||0);if(!revision)return{revision:0,data:{customers:[],quotes:[],automation:{version:1,revision:0,orders:[],payments:[],done:{},quoteSent:{},sampleSent:{},log:[]}}};const rows=SpreadsheetApp.openById(DB_ID).getSheetByName(STORE).getDataRange().getValues().slice(1).filter(r=>Number(r[0])===revision).sort((a,b)=>Number(a[1])-Number(b[1]));if(!rows.length)throw Error('공통 저장 원본을 찾을 수 없습니다.');const text=rows.map(r=>String(r[2]).slice(5)).join('');return{revision,data:JSON.parse(text)}}
function dateValue_(v){if(v instanceof Date)return Utilities.formatDate(v,'Asia/Seoul','yyyy-MM-dd');const m=String(v||'').match(/(20\d{2})[.\-/년]\s*(\d{1,2})[.\-/월]\s*(\d{1,2})/);return m?m[1]+'-'+m[2].padStart(2,'0')+'-'+m[3].padStart(2,'0'):''}
function mergeLeads_(data){const sh=SpreadsheetApp.openById(DB_ID).getSheetByName('고객DB');if(!sh||sh.getLastRow()<3)return data;const rows=sh.getRange(3,1,sh.getLastRow()-2,17).getValues();const known=new Set(data.customers.map(c=>c.id));rows.forEach(r=>{if(!r[0])return;const id='DB-'+r[0];if(known.has(id))return;let phone=String(r[4]||'').replace(/\D/g,'');if(/^1[016789]\d{7,8}$/.test(phone))phone='0'+phone;data.customers.push({id,customerCode:String(r[0]),created:dateValue_(r[1]),name:String(r[3]||''),phone,region:r[5],industry:r[6],opening:dateValue_(r[7]),source:r[8],stage:r[10]||'신규',nextContact:dateValue_(r[13]),amount:Number(String(r[14]).replace(/[^\d]/g,''))||0,memo:r[15]});known.add(id)});return data}
function getSnapshot(){authorize_();return withLock_(()=>{const s=read_();s.data=mergeLeads_(s.data);return s})}
function saveSnapshot(expected,data){authorize_();if(!data||!Array.isArray(data.customers)||!Array.isArray(data.quotes)||!data.automation||data.automation.version!==1)throw Error('저장 형식이 올바르지 않습니다.');const text=JSON.stringify(data);if(text.length>5000000)throw Error('자료 크기가 커서 관리자 점검이 필요합니다.');return withLock_(()=>{const props=PropertiesService.getScriptProperties(),revision=Number(props.getProperty('REV')||0);if(Number(expected)!==revision)throw Error('다른 기기에서 수정했습니다. 현재 내용을 백업한 뒤 새로고침해주세요.');const next=revision+1,sh=SpreadsheetApp.openById(DB_ID).getSheetByName(STORE),chunks=[];for(let i=0;i<text.length;i+=30000)chunks.push([next,chunks.length,'JSON:'+text.slice(i,i+30000)]);sh.getRange(sh.getLastRow()+1,1,chunks.length,3).setValues(chunks);SpreadsheetApp.flush();props.setProperty('REV',String(next));return{revision:next}})}
function doGet(){authorize_();const template=HtmlService.createTemplateFromFile('App');template.bootstrap=JSON.stringify(getSnapshot()).replace(/</g,'\\u003c').replace(/\u2028/g,'\\u2028').replace(/\u2029/g,'\\u2029');return template.evaluate().setTitle('멋:테이블 자동화 업무센터').addMetaTag('viewport','width=device-width, initial-scale=1')}
