const {chromium,webkit}=require('playwright');
const assert=require('node:assert/strict'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const root=path.resolve(__dirname,'..'),out=path.join(root,'qa');fs.mkdirSync(out,{recursive:true});
const key=crypto.randomBytes(32),access=key.toString('base64url');
const seed={schema:1,updated:'2026-09-24',target:10000000,orders:[{date:'2026-09-22',number:'QA-OLD',name:'검증용 기존 매장',amount:1000000,paid:500000,balance:500000,size:'1200×800',grade:'중급형',tables:4,chairs:0,cutlery:4,note:'실제 고객 데이터 아님'}],cash:[{date:'2026-09-22',type:'입금',name:'검증용 기존 매장',category:'계약금',amount:500000,note:'테스트'}]};
const iv=crypto.randomBytes(12),cipher=crypto.createCipheriv('aes-256-gcm',key,iv),encrypted=Buffer.concat([cipher.update(JSON.stringify(seed)),cipher.final(),cipher.getAuthTag()]);
const snapshot=JSON.stringify({iv:iv.toString('base64'),data:encrypted.toString('base64')});
const mime={'.html':'text/html','.js':'text/javascript','.css':'text/css','.json':'application/json','.webmanifest':'application/manifest+json'};
const server=http.createServer((req,res)=>{const url=new URL(req.url,'http://localhost');if(url.pathname.endsWith('snapshot.enc.json')){res.setHeader('Content-Type','application/json');return res.end(snapshot);}if(url.pathname.endsWith('.png')||url.pathname.endsWith('.svg')){res.setHeader('Content-Type','image/png');return res.end(Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVQIHWP4z8DwHwAFgAI/ScLbtAAAAABJRU5ErkJggg==','base64'));}const file=path.join(root,decodeURIComponent(url.pathname),url.pathname.endsWith('/')?'index.html':'');if(!file.startsWith(root)||!fs.existsSync(file)){res.statusCode=404;return res.end('not found');}res.setHeader('Content-Type',mime[path.extname(file)]||'text/plain');res.end(fs.readFileSync(file));});
const visible=async(p,selector)=>p.locator(selector).waitFor({state:'visible'});
const hidden=async(p,selector)=>p.locator(selector).waitFor({state:'hidden'});
async function run(engine,name,viewport){const browser=await engine.launch({headless:true,...(process.env.CHROMIUM_EXECUTABLE?{executablePath:process.env.CHROMIUM_EXECUTABLE,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu','--use-gl=angle','--use-angle=swiftshader','--enable-unsafe-swiftshader']}: {})});const context=await browser.newContext({viewport,acceptDownloads:true,serviceWorkers:'block'});const p=await context.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.clock.install({time:new Date('2026-10-06T11:32:30Z')});const url='http://127.0.0.1:'+server.address().port+'/ledger/';await p.goto(url+'#key='+access);await visible(p,'#app');assert.equal(await p.locator('#month').inputValue(),'2026-10');assert.equal(await p.locator('#revenue').innerText(),'0원');assert.equal(await p.locator('#balance').innerText(),'500,000원');
 await p.click('#addOrder');await p.fill('#orderName','검증용 10월 매장');await p.fill('#orderNumber','QA-OCT');await p.fill('#orderAmount','2000000');await p.fill('#orderSize','테이블 10개');await p.fill('#initialAmount','500000');await p.click('#orderForm button[type=submit]');await hidden(p,'#orderDialog');assert.equal(await p.locator('#revenue').innerText(),'2,000,000원');assert.equal(await p.locator('#received').innerText(),'500,000원');
 await p.reload();await visible(p,'#app');assert.equal(await p.locator('#revenue').innerText(),'2,000,000원');assert.equal(await p.locator('#balance').innerText(),'2,000,000원');
 await p.selectOption('#month','2026-09');await p.click('#closeMonth');await p.click('#confirmYes');await hidden(p,'#confirmDialog');assert.equal(await p.locator('#month').inputValue(),'2026-10');
 await p.click('#showUnpaid');await p.locator('details').filter({hasText:'검증용 기존 매장'}).locator('summary').click();await p.locator('details').filter({hasText:'검증용 기존 매장'}).getByRole('button',{name:'입금 기록'}).click();await p.fill('#cashAmount','500000');await p.click('#cashForm button[type=submit]');await hidden(p,'#cashDialog');assert.equal(await p.locator('#received').innerText(),'1,000,000원');assert.equal(await p.locator('#balance').innerText(),'1,500,000원');
 await p.selectOption('#month','2026-09');assert.equal(await p.locator('#received').innerText(),'500,000원');assert.equal(await p.locator('#addOrder').isDisabled(),true);assert.equal(await p.locator('#balance').innerText(),'0원');
 await p.selectOption('#month','2026-10');await p.click('[data-tab="orders"]');await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,name+'-october.png'),fullPage:true});
 const downloadPromise=p.waitForEvent('download');await p.click('#exportBackup');const download=await downloadPromise;const backup=path.join(out,name+'-backup.json');await download.saveAs(backup);const raw=fs.readFileSync(backup,'utf8');assert(!raw.includes('검증용'));const envelope=JSON.parse(raw);assert.equal(envelope.format,'meot-ledger-backup');
 await p.click('#closeMonth');await p.click('#confirmYes');await hidden(p,'#confirmDialog');assert.equal(await p.locator('#month').inputValue(),'2026-11');assert.equal(await p.locator('#revenue').innerText(),'0원');assert.equal(await p.locator('#balance').innerText(),'1,500,000원');await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,name+'-november.png'),fullPage:true});
 await p.locator('#backupFile').setInputFiles(backup);await visible(p,'#confirmDialog');await p.click('#confirmYes');await hidden(p,'#confirmDialog');assert.equal(await p.locator('#month').inputValue(),'2026-10');assert.equal(await p.locator('#addOrder').isDisabled(),false);assert.equal(await p.locator('#revenue').innerText(),'2,000,000원');
 // Storage failure never reports success and does not discard the user's draft.
 await p.evaluate(()=>{window.realWrite=MeotLedgerStore.write;MeotLedgerStore.write=async()=>{throw Error('검증용 저장 공간 부족');};});await p.click('#addCash');await p.selectOption('#cashType','출금');await p.fill('#cashName','검증용 운송');await p.fill('#cashCategory','배송비');await p.fill('#cashAmount','100000');await p.click('#cashForm button[type=submit]');await p.locator('#cashError').filter({hasText:'저장 공간 부족'}).waitFor();assert.equal(await p.locator('#cashAmount').inputValue(),'100000');assert.equal(await p.locator('#spent').innerText(),'0원');await p.evaluate(()=>MeotLedgerStore.write=window.realWrite);await p.click('#cashForm button[type=submit]');await hidden(p,'#cashDialog');assert.equal(await p.locator('#spent').innerText(),'100,000원');
 // Two stale tabs cannot silently overwrite each other.
 const second=await context.newPage();await second.clock.install({time:new Date('2026-10-06T11:32:30Z')});await second.goto(url);await visible(second,'#app');await p.click('#editTarget');await p.fill('#targetAmount','12000000');await p.click('#targetForm button[type=submit]');await hidden(p,'#targetDialog');await second.click('#editTarget');await second.fill('#targetAmount','13000000');await second.click('#targetForm button[type=submit]');await second.locator('#targetError').filter({hasText:'다른 창'}).waitFor();await second.evaluate(()=>{window.onbeforeunload=null;});await second.close({runBeforeUnload:false});await p.reload();await visible(p,'#app');assert.match(await p.locator('#goalText').innerText(),/12,000,000/);
 const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth);assert.equal(overflow,false,name+' horizontal overflow');assert.deepEqual(errors,[]);await p.evaluate(()=>scrollTo(0,0));await p.screenshot({path:path.join(out,name+'-final.png'),fullPage:true});await context.close();await browser.close();console.log(name+': migration, save/reload, previous-month receipt, close/rollover, encrypted backup/restore, storage failure, conflict and responsive checks PASS');}
server.listen(0,'127.0.0.1',async()=>{try{await run(chromium,'chrome-mobile',{width:390,height:844});await run(chromium,'chrome-small-mobile',{width:360,height:780});await run(chromium,'chrome-desktop',{width:1440,height:1000});}catch(e){console.error(e);process.exitCode=1;}finally{server.close();}});
