const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs'),path=require('node:path');
const root=path.resolve(__dirname,'..'),read=p=>fs.readFileSync(path.join(root,p),'utf8');
function env({clipboard,legacy=false,secure=true,fetchImpl}={}){
 const calls=[],events=[],timers=new Map();let seq=0;
 const window={isSecureContext:secure,meotAnalytics:{track:n=>events.push(n)}},navigator={};
 if(clipboard)navigator.clipboard={writeText:clipboard};
 const document={activeElement:{focus(){}},addEventListener(){},body:{appendChild(){}},execCommand:()=>legacy,createElement:()=>({style:{},select(){},setSelectionRange(){},remove(){}})};
 const context={window,navigator,document,URL,URLSearchParams,AbortController,Promise,Error,console,location:{href:'https://meottable.github.io/meot-table/',assign:u=>calls.push(u)},setTimeout:fn=>{const id=++seq;timers.set(id,fn);return id;},clearTimeout:id=>timers.delete(id),fetch:fetchImpl||(()=>Promise.resolve({type:'opaque',status:0}))};
 vm.createContext(context);return {context,window,calls,events,timers};
}
function options(){return {text:'[예상견적]\n수저통: 필요해요\n의자 별도',href:'https://pf.kakao.com/_BZeSX/chat?bot=true',button:{disabled:false,setAttribute(){},removeAttribute(){}},status:{textContent:''},fallback:{hidden:true},textarea:{value:'',focus(){},select(){}}};}
test('copy succeeds before navigation and preserves bot parameter',async()=>{let copied;const e=env({clipboard:async t=>{copied=t;assert.equal(e.calls.length,0);}});vm.runInContext(read('contact-flow.js'),e.context);const o=options();assert.equal(await e.window.meotContactFlow.copyAndOpen(o),true);assert.equal(copied,o.text);assert.equal(e.calls[0],o.href);assert.equal(o.button.disabled,false);});
test('rejected clipboard and legacy copy show full manual fallback without navigation',async()=>{const e=env({clipboard:async()=>{throw Error('denied');}});vm.runInContext(read('contact-flow.js'),e.context);const o=options();assert.equal(await e.window.meotContactFlow.copyAndOpen(o),false);assert.equal(e.calls.length,0);assert.equal(o.textarea.value,o.text);assert.equal(o.fallback.hidden,false);assert.equal(o.button.disabled,false);});
test('legacy clipboard supported when modern API is unavailable',async()=>{const e=env({legacy:true});vm.runInContext(read('contact-flow.js'),e.context);assert.equal(await e.window.meotContactFlow.copyAndOpen(options()),true);assert.equal(e.calls.length,1);});
test('hung clipboard is bounded and falls back without a false copy claim',async()=>{const e=env({clipboard:()=>new Promise(()=>{})});vm.runInContext(read('contact-flow.js'),e.context);const o=options(),pending=e.window.meotContactFlow.copyAndOpen(o);e.timers.values().next().value();assert.equal(await pending,false);assert.equal(e.calls.length,0);assert.equal(o.fallback.hidden,false);});
test('double tap does not copy or navigate twice',async()=>{let release,copies=0;const e=env({clipboard:()=>{copies++;return new Promise(r=>release=r);}});vm.runInContext(read('contact-flow.js'),e.context);const o=options(),first=e.window.meotContactFlow.copyAndOpen(o);assert.equal(await e.window.meotContactFlow.copyAndOpen(o),false);release();await first;assert.equal(copies,1);assert.equal(e.calls.length,1);});
test('opaque response is explicitly unconfirmed, never saved',async()=>{const e=env();vm.runInContext(read('lead-db.js'),e.context);const r=await e.window.meotLeadDb.save({phone:'01000000000'});assert.equal(r.status,'unconfirmed');assert.deepEqual(e.events,['lead_request_sent']);assert.equal(e.timers.size,0);});
test('invalid phone sends no request',async()=>{let sent=0;const e=env({fetchImpl:()=>{sent++;}});vm.runInContext(read('lead-db.js'),e.context);await assert.rejects(e.window.meotLeadDb.save({phone:'1'}));assert.equal(sent,0);});
test('network failure never emits saved or sent success',async()=>{const e=env({fetchImpl:()=>Promise.reject(Error('network'))});vm.runInContext(read('lead-db.js'),e.context);await assert.rejects(e.window.meotLeadDb.save({phone:'01000000000'}));assert.deepEqual(e.events,[]);assert.equal(e.timers.size,0);});
test('timeout cancels waiting without declaring storage failure or success',async()=>{const e=env({fetchImpl:(_,o)=>new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>reject(Error('abort'))))});vm.runInContext(read('lead-db.js'),e.context);const pending=e.window.meotLeadDb.save({phone:'01000000000'});e.timers.values().next().value();await assert.rejects(pending);assert.deepEqual(e.events,[]);});
test('homepage removal, accessibility controls and script order are complete',()=>{const html=read('index.html');assert.doesNotMatch(html,/layout-consultation|도면|배치 상담|공간 설계/);assert.match(html,/견적 복사하고 카카오 열기/);assert.match(html,/자동 발송되지는 않습니다/);assert(html.indexOf('contact-flow.js')<html.indexOf('homepage-v3.js'));const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.equal(ids.length,new Set(ids).size);for(const id of ['copy-quote','quote-copy-fallback','quote-copy-text','quote-chat-status','consultFallback','consult-copy-chat','consult-copy-manual','consult-copy-text'])assert(ids.includes(id));assert.equal((html.match(/class="serviceCard"/g)||[]).length,3);assert.match(html,/tel:010-6292-8562/);assert.match(html,/10초 예상견적/);});
test('all changed inline and external scripts parse and no false completion remains',()=>{for(const p of ['homepage-v3.js','lead-db.js','contact-flow.js'])new vm.Script(read(p));for(const p of ['index.html','analysis.html'])for(const m of read(p).matchAll(/<script\b([^>]*)>([\s\S]*?)<\/script>/g)){if(!/src=|application\/ld\+json/.test(m[1]))new vm.Script(m[2]);}assert.doesNotMatch(read('homepage-v3.js'),/전송 완료|상담 내용을 전송했습니다|track\('form_submit'/);assert.doesNotMatch(read('lead-db.js'),/track\('lead_saved'/);});
