/* Additive automation workspace. Existing customer and quote stores remain intact. */
(function(){
'use strict';
const E=window.MeotAutomation, KEY=window.MEOT_CLOUD?'meot_cloud_automation_v1':'meot_automation_v1';
let state,broken=false,tab='today',toastTimer;
try{state=E.validate(JSON.parse(localStorage.getItem(KEY)||JSON.stringify(E.empty())))}catch(e){state=E.empty();broken=true}
const html=esc, cash=won, date=today, uuid=()=>crypto.randomUUID();
const page=document.createElement('section');page.className='page';page.id='automation';document.querySelector('main').append(page);
const nav=document.createElement('button');nav.dataset.page='automation';nav.innerHTML='<span>⚡</span>자동화';nav.onclick=()=>go('automation');document.querySelector('.nav').append(nav);
const originalGo=go;go=function(id){originalGo(id);if(id==='automation'){$('topTitle').textContent='자동화 업무센터';render()}};
const originalRender=renderAll;renderAll=function(){originalRender();if(page.classList.contains('on'))render()};
const fast=document.createElement('button');fast.className='btn gold';fast.textContent='자동화 업무센터 열기 →';fast.onclick=()=>go('automation');document.querySelector('#dashboard .page-head').append(fast);
const dialog=document.createElement('dialog');dialog.className='auto-dialog';dialog.innerHTML='<div id="autoDialogBody"></div>';document.body.append(dialog);
const toast=document.createElement('div');toast.className='auto-toast';toast.setAttribute('role','status');toast.hidden=true;document.body.append(toast);
function notice(t){toast.textContent=t;toast.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.hidden=true,6000)}
function latest(){return E.validate(JSON.parse(localStorage.getItem(KEY)||JSON.stringify(E.empty())))}
function change(label,fn){if(broken){notice('저장 자료를 읽지 못해 변경을 중지했습니다. 원본 백업을 먼저 받아주세요.');return false}try{const next=latest();fn(next);next.revision=(next.revision||0)+1;next.log.unshift({id:uuid(),at:new Date().toISOString(),text:label});localStorage.setItem(KEY,JSON.stringify(next));window.dispatchEvent(new CustomEvent('meot:stored'));state=next;render();notice(label);return true}catch(e){notice(e.message||'저장하지 못했습니다.');return false}}
function button(label,action,id='',cls='light'){return '<button type="button" class="btn '+cls+'" data-action="'+action+'" data-id="'+html(id)+'">'+label+'</button>'}
function card(label,value,note){return '<article class="card"><div class="label">'+label+'</div><div class="auto-money">'+value+'</div><p class="auto-note">'+note+'</p></article>'}
function currentTasks(){return E.tasks(state,customers,quotes,date())}
function render(){const orders=state.orders.filter(o=>!o.cancelled),paid=state.payments.filter(p=>!p.voided).reduce((n,p)=>n+p.amount,0),due=orders.reduce((n,o)=>n+E.balance(state,o),0);page.innerHTML='<div class="auto-banner"><h2>멋:테이블 자동화 업무센터</h2><p>문의 → 견적 → 계약 → 입금 → 제작 → 배송 → 후기<br>기록을 바탕으로 다음 할 일과 잔금을 자동 계산합니다.</p></div><p class="auto-alert">'+(window.MEOT_CLOUD?'현재 저장: Google 공통 DB · 상단 저장 상태를 확인하세요.':'현재 저장: 이 기기·이 브라우저 · 공통 DB 연결 전')+'<br>카카오·은행 자동 연동 전입니다. 실제 발송과 입금 확인은 담당자가 진행합니다.</p>'+(broken?'<p class="auto-alert">저장 자료 오류: 변경을 중지했습니다. 설정에서 원본 백업을 받으세요.</p>':'')+'<div class="cards">'+card('오늘 확인',currentTasks().length+'건','재연락·출고·후기')+card('계약 주문',orders.length+'건','견적과 구분한 확정 주문')+card('확인 입금',cash(paid),'담당자가 확인한 기록')+card('남은 잔금',cash(due),'계약액 − 유효 입금')+'</div><div class="auto-tabs">'+[['today','오늘 할 일'],['orders','주문·입금'],['quotes','견적 연결'],['settings','설정·기록']].map(([id,label])=>'<button class="btn light" data-action="tab" data-id="'+id+'" aria-pressed="'+(tab===id)+'">'+label+'</button>').join('')+'</div><div id="autoContent">'+(tab==='today'?todayView():tab==='orders'?ordersView():tab==='quotes'?quotesView():settingsView())+'</div>'}
function todayView(){const tasks=currentTasks();return '<article class="panel"><div class="auto-actions">'+button('일일 요약 보기','report')+button('고객 관리','customers')+'</div>'+(tasks.length?tasks.map(t=>'<div class="auto-task"><div><b>'+html(t.title)+'</b><p>'+html(t.due)+' · '+(t.type==='ship'?'주문 상태 확인':'연락 초안 준비됨')+'</p></div><div class="auto-actions">'+button(t.type==='ship'?'주문 보기':'문구 확인','taskDraft',t.key)+button('처리 완료','done',t.key)+'</div></div>').join(''):'<div class="empty">오늘 예정된 일이 없습니다.<br>고객의 다음 연락일, 견적 발송일, 배송 완료일을 기록하면 자동으로 표시됩니다.</div>')+'</article>'}
function ordersView(){const orders=state.orders.filter(o=>!o.cancelled);return orders.length?'<div class="auto-grid">'+orders.map(o=>{const q=quotes.find(q=>q.id===o.quoteId),changed=q&&E.fingerprint(q)!==o.fingerprint,next={'계약 확인':'제작중','제작중':'출고 준비','출고 준비':'배송 완료'}[o.stage];return '<article class="auto-order"><span class="badge">'+html(o.stage)+'</span><h3>'+html(o.customer)+'</h3><p>'+html(o.quoteNumber)+' · '+html(o.quote.size)+' · '+html(o.quote.grade)+'<br>테이블 '+html(o.quote.tableQty)+'개 / 의자 '+html(o.quote.chairQty||0)+'개<br>출고 예정 '+html(o.quote.shipDate||'미정')+'</p><div class="auto-money">잔금 '+cash(E.balance(state,o))+'</div><p>계약 '+cash(o.total)+' · 입금 '+cash(o.total-E.balance(state,o))+'<br>배송비·추가비는 계약 전 견적에 포함 여부를 확인하세요.</p>'+(changed?'<p class="auto-alert">원본 견적이 계약 후 변경됐습니다. 기존 계약 금액은 유지됩니다. 변경 내용을 확인하기 전 단계 진행을 중지합니다.</p>':'')+'<div class="auto-checks">'+[['spec','규격·등급·수저통 고객 확인'],['schedule','공장 제작·출고 일정 확인'],['quality','검수·포장 완료'],['address','배송지·연락처 확인']].map(([k,v])=>'<label><input type="checkbox" data-check="'+k+'" data-order="'+html(o.id)+'" '+(o.checks[k]?'checked':'')+(o.stage==='배송 완료'?' disabled':'')+'>'+v+'</label>').join('')+'</div><div class="auto-actions">'+button('입금 기록','payment',o.id)+button('입금 내역','payments',o.id)+button('발주문 확인','factory',o.id)+(next&&!changed?button(next+' 확인','stage',o.id,'gold'):'')+(changed?button('계약 변경 확인','amend',o.id):'')+(o.stage==='계약 확인'?button('주문 취소','cancel',o.id):'')+'</div></article>'}).join('')+'</div>':'<article class="panel empty">확정 주문이 없습니다.<br>견적 연결에서 고객이 확정한 견적을 주문으로 등록하세요.</article>'}
function quotesView(){return '<p class="auto-note">견적 금액과 규격을 확인한 뒤 계약으로 등록하세요. 견적 발송일 +2일에 후속 연락이 표시됩니다.</p><div class="auto-actions">'+button('기존 견적 관리','quotes')+button('샘플 발송일 기록','sample')+'</div><div class="auto-grid" style="margin-top:16px">'+quotes.map(q=>'<article class="auto-order"><span class="badge">'+html(q.status||'견적')+'</span><h3>'+html(q.customer)+'</h3><p>'+html(q.number)+' · '+html(q.size)+' · '+html(q.grade)+'</p><div class="auto-money">'+cash(q.grand)+'</div><p>발송일 '+html(state.quoteSent[q.id]||'미기록')+'</p><div class="auto-actions">'+button('발송일 기록','sent',q.id)+(state.orders.some(o=>o.quoteId===q.id&&!o.cancelled)?'<span class="badge">주문 등록됨</span>':button('계약 확정 → 주문','contract',q.id,'gold'))+'</div></article>').join('')+'</div>'+(quotes.length?'':'<article class="panel empty">기존 견적 관리에서 견적을 작성하세요.</article>')}
function settingsView(){return '<div class="auto-settings">'+[['자동 계산 중','계약 중복 방지 · 입금 합산 · 잔금 계산 · 출고 체크 · 후속 연락 일정 · 오늘 업무 요약'],['연락 일정','견적 발송 +2일 · 샘플 발송 +3일 · 배송 완료 +7일 후기 요청. 화면을 열거나 새로고침하면 계산합니다. 앱을 닫은 상태의 알림은 아직 연결 전입니다.'],['연결 필요',(window.MEOT_CLOUD?'':'Google 공통 저장, ')+'카카오 메시지 발송, 은행 거래 조회, 정시 보고 발송은 아직 연결되지 않았습니다. 도면 2D·3D 생성은 별도 검토 업무입니다.'],['원가·이익','현재 기록은 계약액·입금액·잔금입니다. 제작원가와 배송원가가 없으므로 이익으로 표시하지 않습니다.']].map(([a,b])=>'<div class="auto-rule"><b>'+a+'</b><p>'+b+'</p></div>').join('')+'<div class="auto-rule"><b>백업·복원</b><p>고객·견적·주문·입금 기록을 함께 백업합니다. 복원은 같은 자료의 복구용이며, 다른 기기 자료와 자동 합쳐지지 않습니다.</p><div class="auto-actions">'+button('전체 백업 받기','backup')+button('백업 복원','restore')+'</div><input id="autoRestore" type="file" accept="application/json" hidden></div><div class="auto-rule"><b>완료한 할 일</b>'+Object.entries(state.done).slice(-30).map(([k,v])=>'<p>'+html(v.title||k)+button('다시 열기','reopen',k)+'</p>').join('')+'</div><div class="auto-rule"><b>최근 처리 기록</b><div class="auto-log">'+state.log.slice(0,80).map(l=>'<p>'+html(new Date(l.at).toLocaleString('ko-KR',{timeZone:'Asia/Seoul'}))+' · '+html(l.text)+'</p>').join('')+'</div></div></div>'}
function open(body){$('autoDialogBody').innerHTML=body;dialog.showModal()}
function footer(label='저장'){return '<div class="auto-actions"><button class="btn gold" type="submit">'+label+'</button><button class="btn light" type="button" data-close>닫기</button></div>'}
function draft(title,text){open('<h3>'+html(title)+'</h3><p class="auto-note">초안입니다. 확인 후 직접 보내주세요.</p><textarea id="autoDraft" aria-label="문구 초안">'+html(text)+'</textarea><div class="auto-actions">'+button('문구 복사','copy')+'<button class="btn light" data-close>닫기</button></div>')}
function dated(title,onSave){open('<form id="autoDateForm"><h3>'+html(title)+'</h3><label>실제 처리일<input name="date" type="date" required max="'+date()+'" value="'+date()+'"></label>'+footer()+'</form>');$('autoDateForm').onsubmit=e=>{e.preventDefault();const d=e.target.elements.date.value;if(!E.day(d)||d>date())return notice('오늘까지의 실제 처리일을 입력해주세요.');if(onSave(d))dialog.close()}}
function order(id){return state.orders.find(o=>o.id===id&&!o.cancelled)}
function report(){const os=state.orders.filter(o=>!o.cancelled),ps=state.payments.filter(p=>!p.voided&&p.date===date());draft('오늘 업무 요약',['[멋:테이블 '+date()+' 업무 요약]',window.MEOT_CLOUD?'저장 범위: Google 공통 DB':'저장 범위: 이 기기·이 브라우저','고객 '+customers.length+'명 / 견적 '+quotes.length+'건','계약 주문 '+os.length+'건','오늘 확인 입금 '+cash(ps.reduce((n,p)=>n+p.amount,0)),'총 잔금 '+cash(os.reduce((n,o)=>n+E.balance(state,o),0)),'','■ 오늘 할 일',...currentTasks().map(t=>'• '+t.title+' ('+t.due+')'),'','카카오·은행 자동 연결 전. 발송 전 검토가 필요합니다.'].join('\n'))}
async function act(action,id){const o=order(id),q=quotes.find(q=>q.id===id);switch(action){
case 'tab':tab=id;render();break;
case 'customers':case 'quotes':go(action);break;
case 'report':report();break;
case 'contract':if(q&&confirm(q.customer+' / '+cash(q.grand)+'\n고객과 계약 금액·규격·배송비 포함 여부를 확인했나요?'))change('계약 주문 등록: '+q.number,s=>E.contract(s,q,uuid(),new Date().toISOString()));break;
case 'sent':if(q)dated('견적 실제 발송일',d=>change('견적 발송일 기록: '+q.number,s=>{s.quoteSent[q.id]=d}));break;
case 'sample':open('<form id="autoSample"><h3>샘플 실제 발송일</h3><label>고객<select name="customer" required><option value="">고객 선택</option>'+customers.map(c=>'<option value="'+html(c.id)+'">'+html(c.name)+' · '+html(c.customerCode||'')+'</option>').join('')+'</select></label><label>발송일<input name="date" type="date" value="'+date()+'" max="'+date()+'" required></label>'+footer()+'</form>');$('autoSample').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(!E.day(d.date)||d.date>date())return notice('실제 발송일을 확인해주세요.');if(change('샘플 발송일 기록',s=>{s.sampleSent[d.customer]=d.date}))dialog.close()};break;
case 'payment':if(!o)return;open('<form id="autoPayment"><h3>'+html(o.customer)+' 입금 확인 기록</h3><p>잔금 '+cash(E.balance(state,o))+' · 은행 내역을 직접 확인한 뒤 기록하세요.</p><label>확인한 입금액 (원)<input name="amount" type="number" min="1" max="'+E.balance(state,o)+'" step="1" required></label><label>입금일<input name="date" type="date" max="'+date()+'" value="'+date()+'" required></label><label>거래번호 또는 입금자·확인 메모<input name="ref" maxlength="200" required></label>'+footer('입금 확인 저장')+'</form>');const pid=uuid();$('autoPayment').onsubmit=e=>{e.preventDefault();const d=Object.fromEntries(new FormData(e.target));if(d.date>date())return notice('미래 입금은 확인 기록으로 저장할 수 없습니다.');if(change('입금 확인: '+o.quoteNumber,s=>E.payment(s,o.id,d.amount,d.date,d.ref,pid)))dialog.close()};break;
case 'payments':if(!o)return;open('<h3>입금 기록 · '+html(o.customer)+'</h3>'+state.payments.filter(p=>p.orderId===id).map(p=>'<p>'+html(p.date)+' · '+cash(p.amount)+' · '+html(p.ref)+(p.voided?' <b>취소됨</b>':button('오입력 취소','void',p.id))+'</p>').join('')+'<p class="auto-note">오입력 취소는 은행 환불이 아닙니다. 원본 기록은 보존됩니다.</p><button class="btn light" data-close>닫기</button>');break;
case 'void':if(confirm('이 입금 기록이 오입력임을 확인했나요? 잔금이 다시 늘어납니다.')){if(change('오입력 입금 기록 취소',s=>{const p=s.payments.find(p=>p.id===id);if(!p||p.voided)throw Error('이미 취소된 기록입니다.');const ord=s.orders.find(o=>o.id===p.orderId);if(ord&&['출고 준비','배송 완료'].includes(ord.stage))throw Error('출고 이후 입금 정정은 별도 확인이 필요합니다.');p.voided=new Date().toISOString()}))dialog.close()}break;
case 'factory':if(!o)return;if(!E.factoryReady(o))return notice('규격·수저통·출고일을 확인해주세요.');draft('공장 발주문',['[멋:테이블 제작 요청 초안]','견적번호: '+o.quoteNumber,'고객/상호: '+o.customer,'규격: '+o.quote.size+' / '+o.quote.grade,'테이블: '+o.quote.tableQty+'개','의자: '+(o.quote.chairQty||0)+'개','수저통: '+o.quote.cutlery+(o.quote.cutlery==='있음'?' '+o.quote.cutleryQty+'개':''),'출고 예정일: '+o.quote.shipDate,'요청사항: '+(o.quote.memo||'없음'),'','규격·색상·도면 및 제작·출고 일정을 확인 부탁드립니다.'].join('\n'));break;
case 'stage':if(!o)return;const next={'계약 확인':'제작중','제작중':'출고 준비','출고 준비':'배송 완료'}[o.stage];const run=d=>change(next+' 확인: '+o.quoteNumber,s=>{const current=s.orders.find(x=>x.id===id),live=quotes.find(q=>q.id===current.quoteId);if(live&&E.fingerprint(live)!==current.fingerprint)throw Error('계약 후 변경된 견적을 먼저 확인해주세요.');E.transition(s,id,next,d)});if(next==='배송 완료')dated('실제 배송 완료일',run);else if(next&&confirm(next+' 단계로 진행한 것을 확인했나요?'))run(date());break;
case 'amend':if(!o)return;const newer=quotes.find(q=>q.id===o.quoteId);if(!newer)return;if(o.stage!=='계약 확인')return notice('제작 시작 후 계약 변경은 별도 검토가 필요합니다.');if(confirm('고객과 변경 계약을 확인했나요? 변경된 금액·규격으로 다시 기록하고 체크리스트를 초기화합니다.'))change('계약 변경 확인: '+o.quoteNumber,s=>{const old=s.orders.find(x=>x.id===id),paid=old.total-E.balance(s,old);if(!E.money(newer.grand)||Number(newer.grand)<=0||Number(newer.grand)<paid)throw Error('변경 계약액은 입금액 이상이어야 합니다.');old.history=old.history||[];old.history.push({at:new Date().toISOString(),quote:old.quote,total:old.total});old.quote=JSON.parse(JSON.stringify(newer));old.total=Number(newer.grand);old.customer=newer.customer;old.fingerprint=E.fingerprint(newer);old.checks={}});break;
case 'cancel':if(o&&confirm('이 주문을 취소할까요? 기록은 남습니다.'))change('주문 취소: '+o.quoteNumber,s=>{const x=s.orders.find(x=>x.id===id);if(x.stage!=='계약 확인'||x.total-E.balance(s,x)>0)throw Error('입금 또는 제작 진행된 주문은 별도 정산이 필요합니다.');x.cancelled=new Date().toISOString()});break;
case 'done':{const t=currentTasks().find(t=>t.key===id);if(t&&confirm('실제로 처리 완료했나요? 메시지는 자동 발송되지 않습니다.'))change('할 일 처리: '+t.title,s=>{s.done[id]={at:new Date().toISOString(),title:t.title}});break}
case 'taskDraft':{const t=currentTasks().find(t=>t.key===id);if(!t)return;if(t.type==='ship'){tab='orders';render();return}const c=customers.find(c=>c.id===t.customerId),qt=quotes.find(q=>q.id===t.quoteId),ord=order(t.orderId),name=c?.name||qt?.customer||ord?.customer||'고객님';const texts={review:'설치한 테이블은 잘 사용하고 계신가요? 괜찮으시다면 사용 후기와 매장 사진을 부탁드려도 될까요? 불편한 점도 편하게 말씀해주세요.',quote:'보내드린 견적에서 궁금하거나 조정이 필요한 부분이 있으실까요? 매장 일정에 맞춰 안내드리겠습니다.',sample:'보내드린 샘플은 확인하셨을까요? 마음에 드는 색상이나 궁금한 점을 알려주세요.',contact:'테이블 상담 건으로 연락드립니다. 오픈 일정과 필요하신 규격·수량을 알려주시면 준비를 도와드리겠습니다.'};draft(t.title,name+' 안녕하세요, 멋:테이블입니다. '+texts[t.type]);break}
case 'copy':try{await navigator.clipboard.writeText($('autoDraft').value);notice('복사했습니다. 실제 발송은 직접 진행해주세요.')}catch(e){$('autoDraft').focus();$('autoDraft').select();notice('문구를 선택했습니다. 직접 복사해주세요.')}break;
case 'reopen':change('완료한 할 일 다시 열기',s=>{delete s.done[id]});break;
case 'backup':backup();break;
case 'restore':$('autoRestore').click();break;
}}
function backup(){const blob=new Blob([JSON.stringify({format:'meot-automation-backup',version:1,exportedAt:new Date().toISOString(),customers,quotes,leads:parse(LKEY),leadStates,dailyConsultations:parse('meot_admin_daily_consultations_v1',{}),automationRaw:localStorage.getItem(KEY),automation:broken?null:state},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='meot-automation-'+date()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
page.addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)act(b.dataset.action,b.dataset.id)});dialog.addEventListener('click',e=>{if(e.target.closest('[data-close]'))dialog.close();const b=e.target.closest('[data-action]');if(b)act(b.dataset.action,b.dataset.id)});
page.addEventListener('change',async e=>{if(e.target.dataset.check){const el=e.target;change('출고 체크 변경',s=>{const o=s.orders.find(o=>o.id===el.dataset.order);if(!o||o.stage==='배송 완료')throw Error('변경할 수 없는 주문입니다.');o.checks[el.dataset.check]=el.checked});render()}if(e.target.id==='autoRestore')await restore(e.target.files[0])});

window.addEventListener('storage',e=>{if([KEY,CKEY,QKEY].includes(e.key)){try{state=latest();customers=parse(CKEY);quotes=parse(QKEY);renderAll()}catch(err){broken=true;render()}}});
window.addEventListener('hashchange',()=>{if(location.hash==='#automation')go('automation')});
window.addEventListener('focus',()=>{if(page.classList.contains('on'))render()});

async function restore(file){try{
if(!file)return;if(file.size>10*1024*1024)throw Error('10MB 이하 백업 파일만 복원할 수 있습니다.');
const d=JSON.parse(await file.text());if(d.format!=='meot-automation-backup'||!Array.isArray(d.customers)||!Array.isArray(d.quotes))throw Error('자동화 전체 백업 파일을 선택해주세요.');E.validate(d.automation);
if(d.customers.some(c=>!c||typeof c.id!=='string')||d.quotes.some(q=>!q||typeof q.id!=='string'))throw Error('고객·견적 형식을 확인해주세요.');
if(!confirm('현재 고객·견적·주문·입금 기록을 백업 내용으로 바꿀까요? 현재 자료 백업을 먼저 받습니다.'))return;backup();
const values={[CKEY]:d.customers,[QKEY]:d.quotes,[KEY]:d.automation,[LKEY]:d.leads||[],meot_lead_states_v2:d.leadStates||{},meot_admin_daily_consultations_v1:d.dailyConsultations||{}};
const before=Object.fromEntries(Object.keys(values).map(k=>[k,localStorage.getItem(k)]));
try{Object.entries(values).forEach(([k,v])=>localStorage.setItem(k,JSON.stringify(v)))}catch(err){Object.entries(before).forEach(([k,v])=>v===null?localStorage.removeItem(k):localStorage.setItem(k,v));throw err}
customers=d.customers;quotes=d.quotes;leadStates=d.leadStates||{};state=d.automation;broken=false;window.dispatchEvent(new CustomEvent('meot:stored'));renderAll();notice('백업 복원 완료');
}catch(err){notice(err.message)}}
const originalRestore=$('restoreFile').onchange;
$('restoreFile').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const d=JSON.parse(await f.text());if(d.format==='meot-automation-backup')return restore(f);return originalRestore(e)}catch(err){notice('올바른 백업 파일을 선택해주세요.')}};

backupData=function(){backup()};
if(location.hash==='#automation')go('automation');else render();
})();
